name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        example: [examples/example_blink.cpp, 
                  examples/example_fsm_cli.cpp,
                  examples/example_blink_stm32.c]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build program for supported boards (Non-Windows)
        if: runner.os != 'Windows'
        run: pio run

      - name: Build program for supported boards (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd /d C:\
          mkdir build
          cd build
          git clone %GITHUB_SERVER_URL%/%GITHUB_REPOSITORY%
          cd %GITHUB_REPOSITORY_NAME%
          pio run